kucc_fair/urls.py
from django.contrib import admin
from django.urls import path, include

import quiz

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('quiz/', include('quiz.urls')),
    path('tournament/', include('tournament.urls')),
]

main/urls.py
from django.urls import path

from main.views import IndexView

app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

quiz/urls.py
from django.urls import path

from quiz import views

app_name = 'quiz'
urlpatterns = [
    path('<int:pk>/question/', views.question, name='question'),
    path('submit/', views.question_submit, name='submit'),
    path('result/', views.result, name='result'),
]

tournament/urls.py
from django.urls import path

from tournament import views

app_name = 'tournament'
urlpatterns = [
    path('<int:pk>/', views.tournament, name='tournament'),
    path('submit/', views.submit, name='submit'),
    path('result/', views.result, name='result'),
]

main/views.py
from django.shortcuts import render
from django.views.generic import ListView

from quiz.models import Quiz


class IndexView(ListView):
    template_name = 'main/index.html'
    model = Quiz

templates/main/common_header.html
<meta charset="UTF-8">
<title>KUCC 동아리 박람회</title>
{% load static %}
<link rel="stylesheet" href="{% static 'main/common.css' %}"/>
<link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-kr.css' rel='stylesheet' type='text/css'>
<link href='//spoqa.github.io/spoqa-han-sans/css/SpoqaHanSans-jp.css' rel='stylesheet' type='text/css'>

templates/main/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'main/common_header.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'main/index.css' %}"/>
</head>
<body>
    <ul>
    {% for quiz in quiz_list %}
            <li style="background: url({{ quiz.image_url }}) no-repeat center/cover">
            {% if quiz.content_type == 'Q' %}
                <a href="{% url 'quiz:question' quiz.id %}">
            {% else %}
                <a href="{% url 'tournament:tournament' quiz.id %}">
            {% endif %}
                    <div class="quiz-cover">
                        <div class="quiz-content">
                            <div class="quiz-title">{{ quiz.name }}</div>
                            <div class="quiz-description">{{ quiz.description }}</div>
                        </div>
                    </div>
                </a>
            </li>
    {% endfor %}
    </ul>
</body>
</html>