kucc_fair/urls.py
from django.contrib import admin
from django.urls import path, include

import quiz

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('quiz/', include('quiz.urls')),
    path('tournament/', include('tournament.urls')),
]

main/urls.py
from django.urls import path

from main.views import IndexView

app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

tournament/urls.py
from django.urls import path

from tournament import views

app_name = 'tournament'
urlpatterns = [
    path('<int:pk>/', views.tournament, name='tournament'),
    path('submit/', views.submit, name='submit'),
    path('result/', views.result, name='result'),
]

tournament/models.py
from django.db import models

# Create your models here.

tournament/views.py
import random
from django.shortcuts import render, redirect
from django.forms import model_to_dict

from quiz.models import Quiz, Question


def submit(request):
    if request.method == 'POST':
        if 'current_quiz' not in request.session:
            return redirect('main:index')

        quiz_pk = request.session['current_quiz']
        current_session = request.session.get(str(quiz_pk), {})
        if not current_session:
            return redirect('main:index')

        selected = None
        for item in current_session['wait_queue'][0:2]:
            if str(item['id']) in request.POST:
                selected = item
        if not selected:
            return redirect('tournament:tournament', pk=quiz_pk)
            
        current_session['next_level_queue'].append(selected)
        current_session['wait_queue'] = current_session['wait_queue'][2:]

        if not current_session['wait_queue']:
            change_to_next_level(current_session)
        request.session[str(quiz_pk)] = current_session

        if int(current_session['level']) == 1:
            return redirect('tournament:result')
    return redirect('tournament:tournament', pk=quiz_pk)


def change_to_next_level(current_session):
        current_session['level'] = int(current_session['level'] / 2)
        current_session['wait_queue'] = current_session['next_level_queue']
        current_session['next_level_queue'] = []
        random.shuffle(current_session['wait_queue'])


def tournament(request, pk):
    current_session = request.session.get(str(pk), None)
    quiz = Quiz.objects.get(pk=pk)
    if not current_session:
        if not quiz or quiz.content_type is not 'W':
            return redirect('main:index')
        else:
            initialize_tournament(request, pk)
            current_session = request.session[str(pk)]
    request.session['current_quiz'] = pk
    context = {
        'questions': current_session.get('wait_queue', [])[0:2],
        'level': current_session['level'],
        'quiz': quiz
    }
    return render(request, 'tournament/tournament.html', context)


def initialize_tournament(request, pk):
    str_pk = str(pk)
    request.session[str_pk] = {
        'level': 16,
        'next_level_queue': []
    }

    # 성능 이슈 있다고 하지만 꺼낼 데이터가 16개밖에 안 되서 사용함
    question_list = Question.objects.filter(quiz=pk).order_by('?').all()
    request.session[str_pk]['wait_queue'] = [model_to_dict(item) for item in question_list[:16]]



def result(request):
    quiz_pk = request.session['current_quiz']
    current_session = request.session.get(str(quiz_pk), None)
    if not current_session:
        return redirect('main:index')
    if current_session.get('level', 0) != 1:
        return redirect('tournament:tournament', pk=quiz_pk)

    context = {
        'winner': current_session['wait_queue'][0]
    }

    del request.session[str(quiz_pk)]
    return render(request, 'tournament/result.html', context)

templates/tournament/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'main/common_header.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'tournament/result.css' %}"/>
</head>
<body>
    <div id="container">
        <div>당신과 오늘 밤을 함께할 음식은..</div>
        <div class="question-title">{{ winner.question }}!</div>
        <img class="question-img" src="{{ winner.image_url }}">
    </div>
</body>
</html>

templates/tournament/tournament.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'main/common_header.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'tournament/tournament.css' %}"/>
</head>
<body>
{% if level == 2 %}
    <div class="header">결승</div>
{% elif level == 4 %}
    <div class="header">준결승</div>
{% else %}
    <div class="header">{{ level }}강</div>
{% endif %}

    <div id="content">
        <form method="post" action="{% url 'tournament:submit' %}">
        {% csrf_token %}
        {% for item in questions %}
            <div class="selection-container" style="background: url({{ item.image_url }}) no-repeat center/cover">
                <div class="selection-text">{{ item.question }}</div>
                <input type="submit" name="{{ item.id }}" value="" class="selection"/>
            </div>
        {% endfor %}
        </form>
    </div>
</body>
</html>