kucc_fair/urls.py
from django.contrib import admin
from django.urls import path, include

import quiz

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('quiz/', include('quiz.urls')),
    path('tournament/', include('tournament.urls')),
]

main/urls.py
from django.urls import path

from main.views import IndexView

app_name = 'main'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
]

quiz/urls.py
from django.urls import path

from quiz import views

app_name = 'quiz'
urlpatterns = [
    path('<int:pk>/question/', views.question, name='question'),
    path('submit/', views.question_submit, name='submit'),
    path('result/', views.result, name='result'),
]

quiz/models.py
from django.db import models


class Quiz(models.Model):
    TYPES = (
        ('Q', 'Quiz'),
        ('W', 'Worldcup')
    )

    name = models.CharField(max_length=50)
    description = models.CharField(max_length=100)
    content_type = models.CharField(max_length=1, default='Q', choices=TYPES)
    image_url = models.CharField(max_length=1000, default='')
    is_showing = models.BooleanField(default=False, null=False)

    def __str__(self):
        return self.name


class Question(models.Model):
    ANSWER = (
        (True, 'Y'),
        (False, 'N')
    )

    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question = models.CharField(max_length=100, null=False)
    score = models.IntegerField(default=1, null=False)
    image_url = models.CharField(max_length=1000, blank=True)
    description = models.CharField(max_length=1000, default="")
    answer = models.BooleanField(default=True, choices=ANSWER)

    def __str__(self):
        return '{} ({})'.format(self.question, str(self.score))

    def __gt__(self, other):
        return self.pk > other

    def __ge__(self, other):
        return self.pk >= other

    def __lt__(self, other):
        return self.pk < other

    def __le__(self, other):
        return self.pk <= other

    def __eq__(self, other):
        return self.pk == other


class Grade(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    text = models.CharField(max_length=100)
    min = models.IntegerField(null=False)
    max = models.IntegerField(null=False)

    def __str__(self):
        return '[{}] ({}~{}) {}'.format(str(self.quiz.name), str(self.min), str(self.max), self.text)

quiz/views.py
import random

from django.db.models import Q
from django.forms import model_to_dict
from django.shortcuts import render, redirect
from quiz.models import Question, Grade, Quiz


def index(request):
    return render(request, 'quiz/index.html')


def question_submit(request):
    if request.method == 'POST':
        if 'current_quiz' not in request.session:
            return redirect('main:index')

        quiz_pk = request.session['current_quiz']
        current_session = request.session.get(str(quiz_pk), {})
        if not current_session:
            return redirect('main:index')

        question = current_session['prev_question']
        submit_list = current_session.get('submit_list', [])
        if question['id'] in [submit['id'] for submit in submit_list]:
            return redirect('quiz:question', pk=quiz_pk)
        question['correct'] = True if str(question['answer']) in request.POST else False
        submit_list.append(question)

        current_session['step'] = current_session.get('step', 0) + 1
        current_session['submit_list'] = submit_list
        request.session[str(quiz_pk)] = current_session
        if current_session['step'] >= 10:
            return redirect('quiz:result')

    return redirect('quiz:question', pk=quiz_pk)


def question(request, pk):
    current_session = request.session.get(str(pk), None)
    if not current_session:
        quiz = Quiz.objects.get(pk=pk)
        if not quiz or quiz.content_type is not 'Q':
            return redirect('main:index')
        else:
            current_session = request.session[str(pk)] = {}
    step = current_session.get('step', 0)
    pick_list = current_session.get('submit_list', [])
    request.session['current_quiz'] = pk

    prev_question_id_list = [item['id'] for item in pick_list]

    # 몇 개 안되서 다 가져와서 랜덤으로 뽑음
    question_list = Question.objects.filter(~Q(pk__in=prev_question_id_list), quiz=pk)
    question = random.choice(question_list)

    current_session['prev_question'] = model_to_dict(question)
    context = {
        'step': step,
        'question': question
    }
    return render(request, 'quiz/quiz.html', context)


def result(request):
    quiz_pk = request.session['current_quiz']
    current_session = request.session.get(str(quiz_pk), None)
    if not current_session:
        return redirect('main:index')

    if 'step' not in current_session or current_session['step'] < 9:
        del request.session[str(quiz_pk)]
        return redirect('main:index')
    pick_list = current_session['submit_list']
    score = 0
    for question in pick_list:
        if question['correct']:
            score += question['score']

    grade = Grade.objects.get(min__lte=score, max__gte=score)
    context = {
        'incorrect_list': list(filter(lambda item: item['correct'] is False, pick_list)),
        'grade': grade.text
    }
    del request.session[str(quiz_pk)]

    return render(request, 'quiz/result.html', context)

templates/quiz/index.html
<!DOCTYPE html>
<html lang="ko">
<head>
    {% include 'main/common_header.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'quiz/index.css' %}"/>
</head>
<body>
    <div id="container">
        <div class="title">{{ quiz.name }}</div>
        <a href="{% url 'quiz:question' %}"><div id="btn-start" class="btn">시작!</div></a>
    </div>
</body>
</html>

templates/quiz/quiz.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'main/common_header.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'quiz/quiz.css' %}"/>
</head>
<body>
    <div id="container">
        <div>
            <h1 class="question">{{ question.question }}</h1>
            {% if question.image_url %}
            <div class="img-container">
                <img class="question-img" src="{{ question.image_url }}"/>
            </div>
            {% endif %}
            <form method="post" action="{% url 'quiz:submit' %}">
                {% csrf_token %}
                <input type="submit" name="True" value="맞아요" class="btn btn-positive"/>
                <input type="submit" name="False" value="아니에요" class="btn btn-negative"/>
            </form>
            <div class="step-container">
                <div class="step">{{ step|add:"1" }}/10</div>
                <progress class="quiz-progress" value="{{ step }}" max="10"></progress>
            </div>
        </div>
    </div>
</body>
</html>

templates/quiz/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'main/common_header.html' %}
    {% load static %}
    <link rel="stylesheet" href="{% static 'quiz/result.css' %}"/>
</head>
<body>
    <div id="cover">
        <div id="result">{{ grade }}</div>
        <div id="anchor">
            {% if incorrect_list|length != 0 %}
                <div id="anchor-text">무엇을 틀렸는지 궁금하신가요?</div>
                <div id="arrow-down"><img src="{% static 'images/arrow-down.png' %}" width="100%"/></div>
            {% else %}
                <div>모든 정답을 맞히셨습니다!</div>
            {% endif %}
        </div>
    </div>
    <ul>
    {% for question in incorrect_list %}
        <li class="question-item">
            <div class="question-content">
                {% if question.image_url %}
                    <img class="question-img" src="{{ question.image_url }}"/>
                {% endif %}
                <div>
                    <div class="question">{{ question.question }}</div>
                    <div class="description">{{ question.description }}</div>
                </div>
            </div>
        </li>
    {% endfor %}
    </ul>
</body>
</html>